apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: index.docker.io/marygabry1508/petclinic:b1.20200413.215026
        name: petclinic
        ports:
        - containerPort: 8080
